# Generated by Django 5.2.3 on 2025-07-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_printers'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(blank=True, to='orders.order', verbose_name='Заказы')),
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='printers.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Время',
                'db_table': 'timelines',
            },
        ),
    ]
