# Generated by Django 5.2.3 on 2025-06-23 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0006_remove_printer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название отчёта')),
                ('start_day', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Начало отчета')),
                ('end_day', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Конец отчета')),
                ('printers', models.ManyToManyField(blank=True, null=True, to='printers.printer', verbose_name='Принтеры')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'reports',
                'ordering': ['-id'],
            },
        ),
    ]
