# Generated by Django 5.2.3 on 2025-06-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default=1, max_length=110, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
