# Generated by Django 5.2.3 on 2025-06-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='printers',
            new_name='printers_at_reports',
        ),
    ]
