# Generated by Django 5.2.3 on 2025-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_remove_printer_orders'),
        ('reports', '0003_rename_printers_report_printers_at_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='printers_at_reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='printers_at_reports', to='printers.printer', verbose_name='Принтеры'),
        ),
    ]
