# Generated by Django 5.2.3 on 2025-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_remove_printer_orders'),
        ('reports', '0004_alter_report_printers_at_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='printers_at_reports',
        ),
        migrations.AddField(
            model_name='report',
            name='printers',
            field=models.ManyToManyField(blank=True, null=True, to='printers.printer', verbose_name='Принтеры'),
        ),
    ]
