# Generated by Django 5.2.3 on 2025-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Принтер')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('serial_number', models.CharField(max_length=300, verbose_name='Серийный номер')),
                ('status', models.CharField(blank=True, choices=[('work', 'В работе'), ('service', 'На обслуживании'), ('repair', 'На починке'), ('ready', 'Готов'), ('broken', 'Сломан')], default='Готов', max_length=50, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printers',
                'ordering': ['-id'],
            },
        ),
    ]
