# Generated by Django 5.2.3 on 2025-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Принтер')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('serial_number', models.CharField(max_length=300, verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printers',
                'ordering': ['-id'],
            },
        ),
    ]
