# Generated by Django 5.2.3 on 2025-06-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_printer_created_at_printer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
    ]
