# Generated by Django 5.2.3 on 2025-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
        ('printers', '0004_alter_printer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='orders.order', verbose_name='Заказы'),
        ),
    ]
