# Generated by Django 5.2.3 on 2025-06-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0005_printer_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='orders',
        ),
    ]
