# Generated by Django 5.2.3 on 2025-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_remove_printer_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.CharField(blank=True, choices=[('work', 'work'), ('service', 'service'), ('repair', 'repair'), ('ready', 'ready'), ('broken', 'broken')], default='ready', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
