# Generated by Django 5.2.3 on 2025-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0007_printer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(blank=True, choices=[('work', 'В работе'), ('service', 'На обслуживании'), ('repair', 'На починке'), ('ready', 'Готов'), ('broken', 'Сломан')], default='Готов', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
