# Generated by Django 5.2.3 on 2025-07-07 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заказ')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Начало выполнения')),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Конец выполнения')),
                ('status', models.CharField(blank=True, choices=[('create', 'Создан'), ('process', 'В работе'), ('complete', 'Выполнен'), ('correction', 'Коррекция'), ('canceled', 'Отменён')], default='Создан', max_length=50, null=True, verbose_name='Статус')),
                ('printers', models.ManyToManyField(blank=True, null=True, to='printers.printer', verbose_name='Принтеры')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-id'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
    ]
