# Generated by Django 5.2.3 on 2025-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заказ')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
