# Generated by Django 5.2.3 on 2025-06-17 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Конец выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Общее время'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Начало выполнения'),
        ),
    ]
