# Generated by Django 5.2.3 on 2025-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='printers',
            field=models.ManyToManyField(blank=True, to='printers.printer', verbose_name='Принтеры'),
        ),
    ]
