# Generated by Django 5.2.3 on 2025-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('process', 'process'), ('complete', 'complete')], default='create', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
