# Generated by Django 5.2.3 on 2025-06-17 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_end_time_order_full_time_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='Общее время'),
        ),
    ]
