# Generated by Django 5.2.3 on 2025-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_printers'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='printers',
            field=models.ManyToManyField(blank=True, to='timeline.timeline', verbose_name='Принтеры'),
        ),
    ]
