# Generated by Django 5.2.3 on 2025-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_time',
            field=models.TimeField(blank=True, editable=False, verbose_name='Общее время'),
        ),
    ]
