# Generated by Django 5.2.3 on 2025-06-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_full_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_time',
        ),
    ]
