# Generated by Django 5.2.3 on 2025-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_printers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
