# Generated by Django 5.2.3 on 2025-06-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='printers',
            new_name='printers_at_orders',
        ),
    ]
