# Generated by Django 5.2.3 on 2025-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_printers_order_printers_at_orders'),
        ('printers', '0006_remove_printer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='printers_at_orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='printers_at_orders', to='printers.printer', verbose_name='Принтеры'),
        ),
    ]
