# Generated by Django 5.2.3 on 2025-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_printers_at_orders_order_printers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('process', 'process'), ('complete', 'complete'), ('correction', 'correction'), ('canceled', 'canceled')], default='create', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
