# Generated by Django 5.2.3 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'Создан'), ('process', 'В работе'), ('complete', 'Выполнен'), ('correction', 'Коррекция'), ('canceled', 'Отменён')], default='Создан', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
