# Generated by Django 5.2.3 on 2025-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
