# Generated by Django 5.2.3 on 2025-06-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
    ]
