# Generated by Django 5.2.3 on 2025-07-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('start_time', 'end_time')},
        ),
    ]
