name: CI for que

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    que:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Show date
              run: date
    
